esphome:
  name: example-zb
  friendly_name: Example Zigbee Coordinator

api:
  encryption:
    key: !secret example_zb__api_encryption_key

ota:
  - platform: esphome
    password: !secret example_zb__ota_password

packages:
  remote_package:
    url: https://github.com/nkings10/esphome-packages
    refresh: 0d
    files:
      - tubezb-cc2652p7-poe-2023/package.yaml
