esphome:
  name: example-bp
  friendly_name: Example Bluetooth Proxy

api:
  encryption:
    key: !secret example_bp__api_encryption_key

ota:
  - platform: esphome
    password: !secret example_bp__ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: Example-BP
    password: !secret example_bp__wifi_ap_password

packages:
  remote_package:
    url: https://github.com/nkings10/esphome-packages
    refresh: 0d
    files:
      - bluetooth-proxy/package.yaml
